particlesJS("particles-js", 
    {"particles":{
            "number":{
                "value":50,
                "density":{
                    "enable":true,
                    "value_area":800
                }
            },
            "color":{
                "value":"#ff0000"
            },
            "shape":{
                "type":"circle",
                "stroke":{
                    "width":5,
                    "color":"#ffffff"
                },
                "image":{
                    "src":"img/github.svg",
                    "width":300,"height":300
                }
            },
            "opacity":{
                "value":0.5,
                "random":false,
                "anim":{
                    "enable":false,
                    "speed":1,
                    "opacity_min":0.1,
                    "sync":false
                }
            },
            "size":{
                "value":3,
                "random":true,
                "anim":{
                    "enable":false,
                    "speed":25.3,
                    "size_min":0.1,"sync":false
                }
            },
            "line_linked":{
                "enable":true,
                "distance":175,
                "color":"#ffffff",
                "opacity":0.6,
                "width":8
            },
            "move":{
                "enable":true,
                "speed":2.5,
                "direction":"bottom",
                "random":true,
                "straight":false,
                "out_mode":"out",
                "bounce":false,
                "attract":{
                    "enable":false,
                    "rotateX":600,
                    "rotateY":1200
                }
            }
        },
        "interactivity":{
            "detect_on":"canvas",
            "events":{
                "onhover":{
                    "enable":true,
                    "mode":"bubble"
                },
                "onclick":{
                    "enable":true,
                    "mode":"repulse"
                },
                "resize":true
            },
            "modes":{
                // during hover/ drag
                "bubble":{
                    "distance":200,
                    "size":20,
                    "duration":1.5,
                    "opacity":0.3,
                    "speed":3
                },
                // during tap
                "repulse":{
                    "distance":200,
                    "duration":0.4
                }
            }
        },
        "retina_detect":true
    }
);